site_name: HengZhao's Knowledge Base
site_url: https://enlzhao.github.io/Notebook
copyright: Copyright &copy; 2022 - 2024 <a href="https://github.com/enlzhao" target="_blank" rel="noopener">æŸå…°</a>
site_author: EnlZhao
site_description: çŸ¥è¯†åº“

# Pages
nav: 
  - Hello: 
    - Hello: index.md
    - å‹é“¾: link.md
  - Course:
    - å‰è¨€: Course/abstract.md
    - è®¡ç®—æœºç³»ç»Ÿâ…¡:
      - è®¡ç®—æœºç³»ç»Ÿâ…¡: Course/System2/index.md
    - è®¡ç®—æœºç³»ç»Ÿâ…¢:
      - è®¡ç®—æœºç³»ç»Ÿâ…¢: Course/System3/index.md
    - æ•°æ®ç»“æ„åŸºç¡€: 
      - æ•°æ®ç»“æ„åŸºç¡€: Course/FDS/index.md
      - ç®—æ³•åˆ†æå’ŒæŠ½è±¡æ•°æ®ç±»å‹: Course/FDS/Lec01.md
      - çº¿æ€§ç»“æ„: Course/FDS/Lec02.md
      - æ ‘: Course/FDS/Lec03.md
      - å›¾: Course/FDS/Lec04.md
      - æ’åº: Course/FDS/Lec05.md
      - å“ˆå¸Œ: Course/FDS/Lec06.md
    - é«˜çº§æ•°æ®ç»“æ„ä¸ç®—æ³•åˆ†æ:
      - é«˜çº§æ•°æ®ç»“æ„ä¸ç®—æ³•åˆ†æ: Course/ADS/index.md
      - æ•°æ®ç»“æ„:
        - AVL & Splay: Course/ADS/Lec01.md
        - Red-Black & B+: Course/ADS/Lec02.md
        - Heap: Course/ADS/Lec03.md
      - ç®—æ³•åˆ†æ:
        - Backtracking: Course/ADS/Lec04.md
        - Divide and Conquer: Course/ADS/Lec05.md
        - Dynamic Programming: Course/ADS/Lec06.md
        - Greedy: Course/ADS/Lec07.md
        - NP - Completeness: Course/ADS/Lec08.md
    - é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡:
      - é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡: Course/OOP/index.md
      - Beginning: Course/OOP/Lec01.md
      - Step in Object-Oriented: Course/OOP/Lec02.md
      - Container: Course/OOP/Lec03.md
      - Object Interactive: Course/OOP/Lec04.md
      - Key Words: Course/OOP/Lec05.md
      - Inheritance & Polymorphism: Course/OOP/Lec06.md
      - Copt Ctor & Overloaded Operators: Course/OOP/Lec07.md
      - Templates: Course/OOP/Lec08.md
      - Exception Handling: Course/OOP/Lec09.md
      - Smart Pointers: Course/OOP/Lec10.md
      - Class Design: Course/OOP/Lec11.md
      - Streams & ç»§æ‰¿æ„é€ å‡½æ•°: Course/OOP/Lec12.md
    # - å¯†ç å­¦:
    #   - å¯†ç å­¦: Course/Crypto/index.md
    #   - æ•°å­¦åŸºç¡€: Course/Crypto/Lec01.md
    #   - å¤å…¸å¯†ç : Course/Crypto/Lec02.md
    - è®¡ç®—æœºåŠ¨ç”»: 
      - è®¡ç®—æœºåŠ¨ç”»: Course/Computer-Animation/index.md
      - ç®€ä»‹: Course/Computer-Animation/1-è®¡ç®—æœºåŠ¨ç”»ç®€ä»‹.md
      - åŠ¨ç”»åŸºæœ¬åŸåˆ™: Course/Computer-Animation/2-åŠ¨ç”»åŸºæœ¬åŸåˆ™.md
      - è€ƒè¯•å¤§çº²: Course/Computer-Animation/FinalExam.md
    # - é¢å‘ä¿¡æ¯å®‰å…¨çš„ä¿¡å·å¤„ç†:
    #   - é¢å‘ä¿¡æ¯å®‰å…¨çš„ä¿¡å·å¤„ç†: Course/Signal-Processing/index.md
    #   - ä¿¡å·ä¸ç³»ç»ŸåŸºç¡€: Course/Signal-Processing/1-ä¿¡å·ä¸ç³»ç»ŸåŸºç¡€.md
    - ç½‘ç»œå®‰å…¨åŸç†ä¸å®è·µ:
      - ç½‘ç»œå®‰å…¨åŸç†ä¸å®è·µ: Course/netsec/index.md
      - DDoS: Course/netsec/ddos.md
      - Route Security: Course/netsec/routesec.md
      - Anonymous Communication: Course/netsec/anonymity.md
      - Web Security: Course/netsec/websec.md
    - ç¼–è¯‘åŸç†:
      - ç¼–è¯‘åŸç†: Course/cp/index.md
      - Introduction: Course/cp/intro.md
      - è¯æ³•åˆ†æ: Course/cp/lexical.md
      - è¯­æ³•åˆ†æ(è‡ªé¡¶å‘ä¸‹): Course/cp/parsing1.md
      - è¯­æ³•åˆ†æ(è‡ªåº•å‘ä¸Š): Course/cp/parsing2.md
  - AI: 
    - Triviality:  
        - Triviality: AI/Triviality/index.md
        - å‡¸ä¼˜åŒ–: AI/Triviality/ConvexOpt.md
        - å¯¹æŠ—æ”»å‡»:
          - å¯¹æŠ—æ”»å‡»: AI/Triviality/AdversarialAttack/index.md
          - FGSM: AI/Triviality/AdversarialAttack/FGSM.md
          - BIM: AI/Triviality/AdversarialAttack/BIM.md
          - PGD: AI/Triviality/AdversarialAttack/PGD.md
        - èŒƒæ•°: AI/Triviality/Norm.md
        - PyTorch: 
          - PyTorch: AI/PyTorch/index.md
          - A 60 Min BLITZ: 
            - A 60 Min BLITZ: AI/PyTorch/BLITZ/index.md
            - Tensors: AI/PyTorch/BLITZ/lec01.md
            - Autograd: AI/PyTorch/BLITZ/lec02.md
            - Neural Networks: AI/PyTorch/BLITZ/lec03.md
            - Training a Classifier: AI/PyTorch/BLITZ/lec04.md
    - ä¼˜åŒ–ç®—æ³•: 
        - ä¼˜åŒ–ç®—æ³•: AI/OptimAlgorithm/index.md
    - å­¦ä¹ å‡†åˆ™: 
        - å­¦ä¹ å‡†åˆ™: AI/LearningCriterion/index.md
    - RelatedCourses:
      - DeepLearning: 
        - DeepLearning: AI/Courses/DeepLearning/index.md
        - Intrucution to Deep Learning: AI/Courses/DeepLearning/introduction.md
        - Neural Networks and Deep Learning: 
          - Neural Networks and Deep Learning: AI/Courses/DeepLearning/course1/index.md
        - Improving Deep Neural Networks: 
          - Improving Deep Neural Networks: AI/Courses/DeepLearning/course2/index.md
        - Structuring Machine Learning Projects: 
          - Structuring Machine Learning Projects: AI/Courses/DeepLearning/course3/index.md
        - Convolutional Neural Networks: 
          - Convolutional Neural Networks: AI/Courses/DeepLearning/course4/index.md
        - Building Sequence Models: 
          - Building Sequence Models: AI/Courses/DeepLearning/course5/index.md
      - CS229: 
        - CS229: AI/Courses/CS229/index.md
  - Triviality: 
    - Markdown: Triviality/markdown.md
    - Missing Semester: 
      - Missing Semester: Triviality/The Missing Semester/index.md
      - Vim: Triviality/The Missing Semester/Vim.md
    - CMake: 
      - CMake: Triviality/CMake/index.md
      - å‡†å¤‡&è¯•ç¼–è¯‘: Triviality/CMake/Lec01.md
      - åˆä½“éªŒ: Triviality/CMake/Lec02.md
  - Tools: 
    - GitHub: 
      - GitHub: Triviality/GitHub/index.md
      - Basics: Triviality/GitHub/Le1.md
      - Git Related: Triviality/GitHub/Git.md

theme:
  name: material
  logo: Icon/Avatar.png
  custom_dir: overrides
  icon: 
    logo: material/airplane # é¡µé¢icon
  font: 
    text: LXGW WenKai Screen #JetBrains Mono
    code: JetBrains Mono
  favicon: Icon/Avatar.png
  admonition:
    note: octicons/tag-16
    abstract: octicons/checklist-16
    info: octicons/info-16
    tip: octicons/squirrel-16
    success: octicons/check-16
    question: octicons/question-16
    warning: octicons/alert-16
    failure: octicons/x-circle-16
    danger: octicons/zap-16
    bug: octicons/bug-16
    example: octicons/beaker-16
    quote: octicons/quote-16
    code: octicons/code-16
  palette:
    - scheme: default
      primary: Kleinland 
      toggle:
        icon: material/toggle-switch
        name: Switch to Light_Pink mode
    - scheme: default
      primary: DustyPeony 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Light_Blue mode
  # å¯¼èˆªæ 
  features:
    - navigation.tracking # åœ¨urlä¸­ä½¿ç”¨æ ‡é¢˜å®šä½é”šç‚¹
    - navigation.tabs # nav top ç›®å½•æ˜¾ç¤ºåœ¨æ ‡é¢˜æ 
    # - navigation.tabs.sticky  # æ»šåŠ¨æ˜¯éšè—é¡¶éƒ¨ navï¼Œéœ€è¦é…åˆ navigation.tabs ä½¿ç”¨
    #- navigation.sections  # navèŠ‚ç‚¹ç¼©è¿›
    #- navigation.expand  # æ¯æ¬¡åˆ·æ–°éƒ½å±•å¼€å­èŠ‚ç‚¹
    - navigation.indexes  # è·Ÿnavigation.instantä¸å…¼å®¹
    #- toc.integrate  # ç›®å½•å±•å¼€åœ¨å­—èŠ‚ç‚¹ä¸‹
    - navigation.top # ä¸€é”®å›é¡¶ top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - header.autohide
    - toc.separate
    - toc.follow
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest

  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡

repo_url: https://github.com/enlzhao/Notebook # å³ä¸Šè§’ç‚¹å‡»è·³è½¬çš„é“¾æ¥
repo_name: Knowledge Base # å³ä¸Šè§’çš„åå­—
## [bottom-left corner]

# [Extensions]
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - encryptcontent:
      title_prefix: '[LOCK]'
      summary: AES encryption supported by unverbuggt@github's plugin
      placeholder: Provide password and press ENTER
      decryption_failure_message: Invalid password
      encryption_info_message: Contact me(Enl_Z) via methods provided in the comments section for access to this page
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs 
  - obsidian-support
  - glightbox
  - statistics
  # - blog
  #- tags # ç»™å•ç¯‡æ–‡ç« æ·»åŠ æ ‡ç­¾ https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  # - git-revision-date-localized: # æ˜¾ç¤ºæœ€åä¸€æ¬¡ä¿®æ”¹æ—¶é—´
  #     type: timeago
  #     enable_creation_date: true

markdown_extensions:
  - toc:  #é”šç‚¹
      permalink: true
      toc_depth: 5
  #ç‹¬ç«‹æœ¯è¯­è¡¨
  - abbr
  - pymdownx.snippets
  #æç¤ºã€è­¦å‘Šæ 
  - admonition
  - pymdownx.details  # æç¤ºå—å¯æŠ˜å 
  - pymdownx.superfences:   # ä»£ç åµŒå¥—åœ¨åˆ—è¡¨é‡Œ
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  #æŒ‰é’®
  - attr_list
  #ä»£ç å—
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite  # è¡Œå†…ä»£ç é«˜äº®
  #å†…å®¹æ ‡ç­¾æ 
  - pymdownx.tabbed:
      alternate_style: true 
  #è¡¨æ ¼
  - tables
  #æ³¨è„š
  - footnotes
  #æ ¼å¼åŒ–å¤„ç†
  - pymdownx.keys
  - pymdownx.mark   # æ–‡æœ¬é«˜äº®
  - pymdownx.tilde  # åˆ é™¤çº¿ä¸‹æ ‡
  - pymdownx.caret  # ä¸‹åˆ’çº¿ä¸Šæ ‡
  - pymdownx.critic # å¢åŠ åˆ é™¤ä¿®æ”¹é«˜äº®æ³¨é‡Šï¼Œå¯ä¿®é¥°è¡Œå†…æˆ–æ®µè½
  #å›¾æ ‡
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #å›¾ç‰‡
  - md_in_html
  #åˆ—è¡¨
  - def_list
  - pymdownx.tasklist:  # å¤é€‰æ¡†checklist
      custom_checkbox: true
  #å…¶ä»–
  - smarty
  - meta
  - sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem  # å¯¹åŠ ç²—å’Œæ–œä½“æ›´å¥½çš„æ£€æµ‹
  - pymdownx.smartsymbols # ç¬¦å·è½¬æ¢
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: EnlZhao
      repo: enlzhao.github.io/Notebook
  - toc:
      permalink:  ğŸ‘€ # âš“ï¸ # æ˜¾ç¤ºé”šç‚¹
  - pymdownx.tasklist:
      custom_checkbox: true  
  - nl2br
  
extra_javascript:
  - assets/javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  

extra_css:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - assets/extra_css/counter.css
  - assets/extra_css/giscus.css
  - assets/extra_css/webcolor.css
  - assets/extra_css/tasklist.css
  - assets/extra_css/flink.css

extra: 
  vssue: Enl_Z
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/enlzhao
      name: GitHub 
    - icon: fontawesome/solid/paper-plane
      link: mailto:hengzhao2002@gmail.com
      name: Outlook 
    - icon: fontawesome/brands/qq
      link: tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=1613715141&website=www.oicqzone.com
      name: QQ 
    - icon: fontawesome/regular/chess-king
      link: https://enlzhao.github.io/
      name: Blog
